accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth import views

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url=reverse_lazy("accounts:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'


urlpatterns = [
    path('', blog_index_view, name='index'),
    path('single/<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat>', blog_index_view, name='category'),
    path('tag/<str:tag>', blog_index_view, name='tag'),
    path('author/<str:author>', blog_index_view, name='author'),
    path('search/', blog_search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]

urlpatterns += debug_toolbar_urls()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
User._meta.get_field('email')._unique = True

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default_img.jpg')
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    counted_views= models.IntegerField(default=0)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})
		
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField(max_length=300)
    is_approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-updated_date']

accounts/forms.py
from django.forms import EmailField, EmailInput
# from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField


class MyUserCreationForm(UserCreationForm):
    captcha = CaptchaField()
    email = EmailField(max_length=100, widget=EmailInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'captcha')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from accounts.forms import MyUserCreationForm
from accounts.backends import EmailOrUsernameModelBackend
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid(): 
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            user_obj = EmailOrUsernameModelBackend()
            user = user_obj.authenticate(request, username, password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                msg = "The entered Username/Email or Password not found! Try entering them again."
                messages.add_message(request, level=messages.ERROR, message=msg)
        else:
            msg = "your Username/Email or Password don't match or exist. Try again."
            messages.add_message(request, messages.ERROR, msg)
        
    form = AuthenticationForm()
    context = {'form':form}
    return render(request, 'accounts/login.html', context)

def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('/accounts/login')
    else:
        logout(request)
        msg = "You have logged out successfully!"
        messages.add_message(request, level=messages.SUCCESS, message=msg)
        return redirect('/')
    
def signup_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            msg = "Your account has been created successfully! Please login."
            messages.add_message(request, level=messages.SUCCESS, message=msg)
            return redirect('/accounts/login')
        else:
            msg = "Entered data is invalid! Try again."
            messages.add_message(request, level=messages.ERROR, message=msg)
    
    form = MyUserCreationForm()
    context = {'form':form}
    return render(request, 'accounts/signup.html', context=context)

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    success_message = """We've emailed you instructions for resetting your password,  
                      if an account exists with the email you entered, You should receive them shortly. 
                      If you don't receive an email,  
                      please make sure you've entered the address you registered with, and check your spam folder."""
    success_url = reverse_lazy('website:index')

templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Log In</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <!-- Showing messages via modals -->
    {% if messages %}
    <div id="messageModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% for message in messages %}
                    <p> {{ message|safe }}</p>
					          {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">OK!</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        window.onload = function () {
            OpenBootstrapPopup();
        };
        function OpenBootstrapPopup() {
            $("#messageModal").modal('show');
        }
    </script>
    {% endif %}

    <!-- Showing form errors via modals -->
    {% if form.errors %}
    <div id="formErrorModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h4>Please fix the following errors</h4>
                    <ul>
                        {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                            {% endfor %}
                        {% endif %}
                        {% endfor %}
                    </ul>
                    {% if form.non_field_errors %}
					    {{ form.non_field_errors }}
				    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">OK!</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        window.onload = function () {
            OpenBootstrapPopup2();
        };
        function OpenBootstrapPopup2() {
            $("#formErrorModal").modal('show');
        }
    </script>
    {% endif %}

{% block content %} 
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}Log In{% endblock %}
{% block content %}

<form class="form-signin" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <a href="/"><img class="mb-4" src="{% static 'img/bootstrap-solid.svg' %}" alt="" width="72" height="72"></a>
    <h1 class="h3 mb-3 font-weight-normal">Sign in to Serenity</h1>
    <label for="inputUsername" class="sr-only">Username/Email</label>
    <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username/Email" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <!-- <div class="checkbox mb-3">
    <label>
        <input type="checkbox" value="remember-me"> Remember me
    </label>
    </div> -->
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <a href="{% url 'accounts:password_reset' %}"><i>Forgot Password?</i></a>

    <p class="mt-5 mb-3 ">Not a user? <a href="/accounts/signup">
    Sign up
    </a></p>
    <p class="mt-5 mb-3 text-muted">&copy; Mohsen Fathali - 2024</p>
</form>
    
{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% block title %}Password Reset{% endblock %}
{% block content %}
<br><br>
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                        <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_email">Email</label>
                                    <input type="email" name="email"  class="form-control"
                                            autocomplete="email" maxlength="254" required id="id_email"
                                            placeholder="Enter email">
                                </div>
                            </div>
                        </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group mt-0 mb-1">
                                    <button type="submit" class="col-md-12 btn btn-dark">Submit
                                    </button>
                                </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'accounts:signup' %}">Create A New Account</a><br><br>
                            <a href="{% url 'accounts:login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password Reset Complete{% endblock %}
{% block content %}
<br><br><br><br><br>
<div class="container my-3 p-3">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                <div class="alert alert-info" role="alert">
                    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}" class="alert-link">Login Here</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Password Reset Confirm{% endblock %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<form class="form-signin" method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    <a href="/"><img class="mb-4" src="{% static 'img/bootstrap-solid.svg' %}" alt="" width="72" height="72"></a>

    <h1 class="h3 mb-3 font-weight-normal">Create your account</h1>

    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
    
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email" required>
    
    <label for="inputFirstname" class="sr-only">First Name</label>
    <input type="text" name="first_name" id="inputFirstname" class="form-control" placeholder="First Name">
    
    <label for="inputLastname" class="sr-only">Last Name</label>
    <input type="text" name="last_name" id="inputLastname" class="form-control" placeholder="Last Name">
    
    <label for="inputPassword1" class="sr-only">Password</label>
    <input style="margin-bottom: 0px"   type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>
    
    <label for="inputPassword2" class="sr-only">Confirm Password</label>
    <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm Password" required>
    
    {{form.captcha}}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>

    <p class="mt-5 mb-3 ">Already have an account? <a href="/accounts/login">
        Sign in
    </a></p>
    <p class="mt-5 mb-3 text-muted">&copy; Mohsen Fathali - 2024</p>
</form>

{% endblock %}