blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'


urlpatterns = [
    path('', blog_index_view, name='index'),
    path('single/<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat>', blog_index_view, name='category'),
    path('tag/<str:tag>', blog_index_view, name='tag'),
    path('author/<str:author>', blog_index_view, name='author'),
    path('search/', blog_search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]

urlpatterns += debug_toolbar_urls()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default_img.jpg')
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    counted_views= models.IntegerField(default=0)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})
		
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField(max_length=300)
    is_approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-updated_date']

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment
from captcha.fields import CaptchaField


class CommentForm(ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = '__all__'

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Post, Category, Tag, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import CommentForm
from django.contrib import messages
from django.utils import timezone

def blog_index_view(request, cat=None, tag=None, author=None):
    posts = Post.objects.filter(post_status=True, published_date__lte= timezone.now())
    if cat:
        posts = posts.filter(categories__name=cat)
    if tag:
        posts = posts.filter(tags__name=tag)
    if author:
        posts = posts.filter(author__username=author)

    p = Paginator(posts, 8)
    if request.method == 'GET':
        try:
            page_number = request.GET.get('page')
            if page_number:
                if int(page_number) > p.num_pages:
                    return redirect(f'/blog/?page={p.num_pages}')
                elif int(page_number) < 1:
                    return redirect('/blog/')
                else:
                    posts = p.page(page_number)
            else:
                posts = p.page(1)

        except PageNotAnInteger:
            # posts = p.page(1).object_list
            # return redirect('/blog/')
            posts = p.get_page(1)
        except EmptyPage:
            # posts = p.page(1).object_list
            # return redirect('/blog/')
            posts = p.get_page(1)
            return redirect('/blog/')
        except ValueError:
            posts = p.get_page(1)
            return redirect('/blog/')

    context = {'posts':posts}
    return render(request, 'blog/blog.html', context)

def blog_single_view(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data.get('name')    
            # email = form.cleaned_data.get('email')    
            # text = form.cleaned_data.get('text')   
            form.save() 
            msg = """Your comment has been successfully received.
            After site admins have approved your comment, it will shown
            on the website."""
            messages.add_message(request, messages.SUCCESS, msg)
        else:
            msg= """Something went wrong! try sending your comment again later."""
            messages.add_message(request, messages.ERROR, msg)

    post = get_object_or_404(Post, id=pid, post_status=True, published_date__lte=timezone.now())
    add_view(pid, post.counted_views)
    post = get_object_or_404(Post, id=pid, post_status=True, published_date__lte=timezone.now())
    
    posts_list = list(Post.objects.filter(post_status=True, published_date__lte= timezone.now()).values('id'))
    posts_list = sorted(posts_list, key=lambda x: x['id'])
    
    query_number = 0
    for dict in posts_list:
        if dict['id'] == pid:
            break
        else:
            query_number += 1

    next_query_number = query_number + 1
    prev_query_number = query_number - 1
    max_id = posts_list[-1]['id']

    if pid == 1:
        next_post_id = posts_list[next_query_number]['id']
        prev_post_id = None
    elif pid == max_id:
        next_post_id = None
        prev_post_id = posts_list[prev_query_number]['id']
    else:
        next_post_id = posts_list[next_query_number]['id']
        prev_post_id = posts_list[prev_query_number]['id']

    cats = Category.objects.filter(post= pid)
    tags = Tag.objects.filter(post= pid)

    comments = Comment.objects.filter(post= pid, is_approved=True)

    form = CommentForm()
    context = {'post': post, 'cats':cats, 'tags':tags, 'form':form, 'comments':comments,
               'next_post_id':next_post_id, 'prev_post_id':prev_post_id}
    return render(request, 'blog/blog-single.html', context)

def blog_search_view(request):
    posts = Post.objects.filter(post_status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains= s) | posts.filter(title__contains= s)
            
    context= {'posts': posts}
    return render(request, 'blog/blog.html', context)

def add_view(pid, counted_views):
    views = counted_views + 1
    post = Post.objects.filter(id= pid).update(counted_views= views)

templates/blog/blog-pagination.html
<div class="blog-pagination">
    <ul class="justify-content-center">
        {% if posts.has_previous %}
        <li><a href="?page=1">&laquo; First</a></li>
        <li><a href="?page={{posts.previous_page_number}}">Prevoius</a></li>
        {% endif %}

        <li class="active"><a href="?page={{posts.number}}">Page {{posts.number}} of {{posts.paginator.num_pages}}</a>
        </li>

        {% if posts.has_next %}
        <li><a href="?page={{posts.next_page_number}}">Next</a></li>
        <li><a href="?page={{ posts.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}
    </ul>
</div>

templates/blog/blog-post-categories.html
<h3 class="sidebar-title">Categories</h3>
<div class="sidebar-item categories">
    {% for cat, cat_counts in categories.items %}
    <ul>
        <li><a href="{% url 'blog:category' cat=cat %}">{{cat}} <span>({{cat_counts}})</span></a></li>
    </ul>
    {% endfor %}
</div><!-- End sidebar categories-->

templates/blog/blog-post-tags.html
<h3 class="sidebar-title">Tags</h3>
<div class="sidebar-item tags">
    <ul>
        {% for t in tags %}
        <li><a href="{% url 'blog:tag' tag=t %}">{{t}}</a></li>
        {% endfor %}
    </ul>
</div><!-- End sidebar tags-->

templates/blog/blog-recent-posts.html
<h3 class="sidebar-title">Recent Posts</h3>
<div class="sidebar-item recent-posts">
    {% for post in posts %}
    <div class="post-item clearfix">
        <img src="{{post.image.url}}" alt="{{post.image}}">
        <h4><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h4>
        <time datetime="2020-01-01">{{post.published_date|date:"d M Y"}}</time>
    </div>
    {% endfor %}

</div><!-- End sidebar recent posts-->

templates/blog/blog-search.html
<h3 class="sidebar-title">Search</h3>
<div class="sidebar-item search-form">
    <form action="{% url 'blog:search' %}" method="get">
        <input type="text" name="s">
        <button type="submit"><i class="bi bi-search"></i></button>
    </form>
</div><!-- End sidebar search formn-->

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block title %}Blog - Single Post{% endblock %}
{% load humanize %}
{% block content %}

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="breadcrumb-hero">
      <div class="container">
        <div class="breadcrumb-hero">
          <h2>Blog</h2>
        </div>
      </div>
    </div>
    <div class="container">
      <ol>
        <li><a href="{% url 'website:index' %}">Home</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li>{{post.title}}</li>
      </ol>
    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Blog Single Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row">

        <div class="col-lg-8 entries">

          <article class="entry entry-single">

            <div class="entry-img">
              <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>

            <h2 class="entry-title">
              <a href="">{{post.title}}</a>
            </h2>

            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author=post.author.username %}">{{post.author.get_full_name}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time
                      datetime="2020-01-01">{{post.published_date|naturalday}}</time></a></li>
                <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{% comments_count post.id %}
                    Comments</a></li>
                <li class="d-flex align-items-center">{{post.counted_views}} views</li>
              </ul>
            </div>

            <div class="entry-content">
              <p>
                {{post.content|safe}}
              </p>

              <!-- <p>
                Sit repellat hic cupiditate hic ut nemo. Quis nihil sunt non reiciendis. Sequi in accusamus harum vel
                aspernatur. Excepturi numquam nihil cumque odio. Et voluptate cupiditate.
              </p>

              <blockquote>
                <p>
                  Et vero doloremque tempore voluptatem ratione vel aut. Deleniti sunt animi aut. Aut eos aliquam
                  doloribus minus autem quos.
                </p>
              </blockquote>

              <p>
                Sed quo laboriosam qui architecto. Occaecati repellendus omnis dicta inventore tempore provident
                voluptas mollitia aliquid. Id repellendus quia. Asperiores nihil magni dicta est suscipit perspiciatis.
                Voluptate ex rerum assumenda dolores nihil quaerat.
                Dolor porro tempora et quibusdam voluptas. Beatae aut at ad qui tempore corrupti velit quisquam rerum.
                Omnis dolorum exercitationem harum qui qui blanditiis neque.
                Iusto autem itaque. Repudiandae hic quae aspernatur ea neque qui. Architecto voluptatem magni. Vel
                magnam quod et tempora deleniti error rerum nihil tempora.
              </p>

              <h3>Et quae iure vel ut odit alias.</h3>
              <p>
                Officiis animi maxime nulla quo et harum eum quis a. Sit hic in qui quos fugit ut rerum atque. Optio
                provident dolores atque voluptatem rem excepturi molestiae qui. Voluptatem laborum omnis ullam quibusdam
                perspiciatis nulla nostrum. Voluptatum est libero eum nesciunt aliquid qui.
                Quia et suscipit non sequi. Maxime sed odit. Beatae nesciunt nesciunt accusamus quia aut ratione
                aspernatur dolor. Sint harum eveniet dicta exercitationem minima. Exercitationem omnis asperiores natus
                aperiam dolor consequatur id ex sed. Quibusdam rerum dolores sint consequatur quidem ea.
                Beatae minima sunt libero soluta sapiente in rem assumenda. Et qui odit voluptatem. Cum quibusdam
                voluptatem voluptatem accusamus mollitia aut atque aut.
              </p>
              <img src="{% static 'img/blog/blog-inside-post.jpg' %}" class="img-fluid" alt="">

              <h3>Ut repellat blanditiis est dolore sunt dolorum quae.</h3>
              <p>
                Rerum ea est assumenda pariatur quasi et quam. Facilis nam porro amet nostrum. In assumenda quia quae a
                id praesentium. Quos deleniti libero sed occaecati aut porro autem. Consectetur sed excepturi sint non
                placeat quia repellat incidunt labore. Autem facilis hic dolorum dolores vel.
                Consectetur quasi id et optio praesentium aut asperiores eaque aut. Explicabo omnis quibusdam esse. Ex
                libero illum iusto totam et ut aut blanditiis. Veritatis numquam ut illum ut a quam vitae.
              </p>
              <p>
                Alias quia non aliquid. Eos et ea velit. Voluptatem maxime enim omnis ipsa voluptas incidunt. Nulla sit
                eaque mollitia nisi asperiores est veniam.
              </p> -->

            </div>

            <div class="entry-footer">
              {% for cat in cats %}
              <i class="bi bi-folder"></i>
              <ul class="cats">
                <li><a href="{% url 'blog:category' cat=cat %}">{{cat}}</a></li>
              </ul>
              {% endfor %}
              <i class="bi bi-tags"></i>
              {% for tag in tags %}
              <ul class="tags">
                <li><a href="{% url 'blog:tag' tag=tag %}">{{tag}}</a></li>
              </ul>
              {% endfor %}
              <br>
              <ul class="cats">
              {% if prev_post_id %}
                <li><a href="{% url 'blog:single' pid=prev_post_id %}">Previous Post</a></li>
              {% endif %}
              </ul>
              <ul class="cats">
              {% if next_post_id %}
                <li><a href="{% url 'blog:single' pid=next_post_id %}">Next Post</a></li>
              {% endif %}
              </ul>
            </div>

          </article><!-- End blog entry -->

          <div class="blog-author d-flex align-items-center">
            <img src="{% static 'img/blog/avatar_young_boy.jpg' %}" class="rounded-circle float-left" alt="">
            <div>
              <h4>{{post.author.get_full_name}}</h4>
              <div class="social-links">
                <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
              </div>
              <p>
                Designed by Mohsen Fathali.
              </p>
            </div>
          </div><!-- End blog author bio -->

          <div class="blog-comments">

            <h4 class="comments-count">{{comments.count}} Comments</h4>
            {% for comment in comments %}
            <div id="comment-1" class="comment">
              <div class="d-flex">
                <div class="comment-img"><img src="{% static 'img/blog/general_user_avatar.png' %}" alt=""></div>
                <div>
                  <h5><a href="">{{comment.name}}</a>
                  </h5>
                  <time datetime="2020-01-01">{{comment.updated_date}}</time>
                  <p>
                    {{comment.text|safe}}
                  </p>
                </div>
              </div>
            </div><!-- End comment #1 -->
            {% endfor %}
            

            <div class="reply-form">
              <h4>Leave a Comment</h4>
              <p>Your email address will not be published. Required fields are marked * </p>
              <form action="{% url 'blog:single' pid=post.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{post.id}}">
                {% if request.user.is_authenticated %}
                  {% if request.user.first_name %}
                    <input name="name" type="hidden" value="{{request.user.first_name}}">
                  {% endif %}
                  {% if request.user.email %}
                    <input name="email" type="hidden" value="{{request.user.email}}">
                  {% endif %}
                {% else %}
                <div class="row">
                  <div class="col-md-6 form-group">
                    <input name="name" type="text" class="form-control" placeholder="Your Name*" required>
                  </div>
                  <div class="col-md-6 form-group">
                    <input name="email" type="email" class="form-control" placeholder="Your Email*" required>
                  </div>
                </div>
                {% endif %}
                <div class="row">
                  <div class="col form-group">
                    <textarea name="text" class="form-control" placeholder="Your Comment*" required></textarea>
                  </div>
                </div>
                <div class="row">
                  <div class="col form-group">
                    {{form.captcha}}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary">Post Comment</button>

              </form>

            </div>

          </div><!-- End blog comments -->

        </div><!-- End blog entries list -->

        <div class="col-lg-4">

          <div class="sidebar">

            {% include 'blog/blog-search.html' %}

            {% post_categories %}

            {% recent_posts 5 %}

            {% post_tags %}

          </div><!-- End sidebar -->

        </div><!-- End blog sidebar -->

      </div>

    </div>
  </section><!-- End Blog Single Section -->

</main><!-- End #main -->

{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block title %}Blog{% endblock %}
{% load humanize %}
{% block content %}

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="breadcrumb-hero">
      <div class="container">
        <div class="breadcrumb-hero">
          <h2>Blog</h2>
        </div>
      </div>
    </div>
    <div class="container">
      <ol>
        <li><a href="{% url 'website:index' %}">Home</a></li>
        <li>Blog</li>
      </ol>
    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row">

        <div class="col-lg-8 entries">
          {% for post in posts %}

          <article class="entry">

            <div class="entry-img">
              <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>

            <h2 class="entry-title">
              <a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
            </h2>

            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                    href="{% url 'blog:author' author=post.author.username %}">{{post.author.get_full_name}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#" ><time
                      datetime="2020-01-01">{{post.published_date|naturalday}}</time></a></li>
                <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{% url 'blog:single' pid=post.id %}">
                  {% comments_count post.id %} Comments</a></li>
                <li class="d-flex align-items-center">{{post.counted_views}} views</li>
              </ul>
            </div>

            <div class="entry-content">
              <p>
                {{post.content|truncatechars:255 |safe}}
              </p>
              <div class="read-more">
                <a href="{% url 'blog:single' pid=post.id %}">Read More</a>
              </div>
            </div>

          </article><!-- End blog entry -->
          {% endfor %}

          {% include 'blog/blog-pagination.html' %}

        </div><!-- End blog entries list -->

        <div class="col-lg-4">

          <div class="sidebar">

            {% include 'blog/blog-search.html' %}

            {% post_categories %}

            {% recent_posts 5 %}

            {% post_tags %}

          </div><!-- End sidebar -->

        </div><!-- End blog sidebar -->

      </div>

    </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->

{% endblock %}